[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "multi_variable_mpc_cbf"
version = "0.1.0"
authors = [
  {name = "Your Name", email = "your.email@example.com"},
]
description = "Multivariable Model Predictive Control with Control Barrier Functions"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy==1.26.4",
    "matplotlib==3.7.1",
    "jax",
    "cvxpy",
    "imageio",
    "psutil",
    "datetime",
    "IPython"
]

[project.urls]
"Homepage" = "https://github.com/yourusername/mpc_cbf"
"Bug Tracker" = "https://github.com/yourusername/mpc_cbf/issues"